# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyAssets',
            fields=[
                ('filename', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=2097152, upload_to='')),
                ('source', models.URLField(max_length=500)),
                ('license', models.CharField(max_length=10)),
                ('license_url', models.URLField()),
            ],
        ),
    ]
