allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@angular-eslint/builder@22.0.0'
  - '@angular-eslint/bundled-angular-compiler@22.0.0'
  - '@angular-eslint/eslint-plugin-template@22.0.0'
  - '@angular-eslint/eslint-plugin@22.0.0'
  - '@angular-eslint/schematics@22.0.0'
  - '@angular-eslint/template-parser@22.0.0'
  - '@angular-eslint/utils@22.0.0'
  - angular-eslint@22.0.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
