# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotaionTable',
            new_name='NotationTable',
        ),
    ]
