# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20161111_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.RecognizedCountry'),
        ),
    ]
