# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='github',
            field=models.CharField(db_index=True, default='none', max_length=39, unique=True),
            preserve_default=False,
        ),
    ]
