# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tasklog_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
