# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20161123_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='angel_co',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hacker_rank',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
