# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20161123_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='angel_co',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hacker_rank',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True),
        ),
    ]
