# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:03
from __future__ import unicode_literals

from django.db import migrations, models, transaction
import uuid


def update_userinfo_id(apps, editor):
    UserInfo = apps.get_model("user", "UserInfo")

    with transaction.atomic():
        for info in UserInfo.objects.all():
            UserInfo.objects.filter(id=info.id).delete()
            info.id = str(uuid.uuid4()).replace("-", "")
            info.save()


def reverse_userinfo_id(apps, editor):
    UserInfo = apps.get_model("user", "UserInfo")

    with transaction.atomic():
        for index, info in enumerate(UserInfo.objects.all()):
            UserInfo.objects.filter(id=info.id).delete()
            info.id = index + 1
            info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20161123_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True)
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.CharField(
                max_length=40, default=uuid.uuid4,
                primary_key=True, serialize=False
            )
        ),
        migrations.RunPython(
            update_userinfo_id, reverse_code=reverse_userinfo_id
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            )
        )
    ]
