# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='availability',
            field=models.CharField(choices=[('FL', 'Available for Full-Time and Part-time position'), ('PT', 'Available for Part-time position only'), ('NA', 'Busy')], db_index=True, default='FL', max_length=2),
            preserve_default=False,
        ),
    ]
