# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20161124_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
