# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20161125_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='users_info',
            field=models.ManyToManyField(related_name='frameworks', to='user.UserInfo'),
        ),
    ]
