# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='user.UserInfo'),
        ),
    ]
