# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20161128_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('primary_name', models.CharField(db_index=True, max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
