# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
