name: Deploy
on:
  push:
    tags:
      - "*"
    branches:
      - "deploy/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: "current"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: |
          pnpm run build --configuration production --no-progress
          cp wrangler.ci.jsonc dist/hysoftware/wrangler.jsonc
      - name: Store built files
        uses: actions/upload-artifact@v7
        with:
          name: hysoftware-dist
          path: dist/hysoftware
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: "current"
      - name: "Download built files"
        uses: actions/download-artifact@v8
        with:
          name: hysoftware-dist
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          command: deploy
          apiToken: ${{ secrets.CLOUD_FLARE_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Invalidate Cloudflare CDN
        run: >
          curl -X POST \
            -H 'Content-Type:application/json' \
            -H "Authorization: Bearer ${CF_TOKEN}" \
            --data '{"purge_everything":true}' \
            https://api.cloudflare.com/client/v4/zones/${FLARE_ZONE}/purge_cache
        env:
          CF_TOKEN: ${{ secrets.CLOUD_FLARE_TOKEN }}
          FLARE_ZONE: ${{ secrets.FLARE_ZONE }}
