name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package-lock.json
          # cache: pnpm
          # cache-dependency-path: pnpm-lock.yaml
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          path: |
            ./node_modules
            ~/.cache/Cypress
      - uses: browser-actions/setup-chrome@latest
      - name: Install essential tools
        run: |
          curl -o ../cc-test-reporter \
              -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod u+x ../cc-test-reporter
      - name: Install Dependencies
        run: npm i
        # run: pnpm i -s
      - name: Lint
        run: npm run lint
        # run: pnpm run lint
      - name: Test
        run: |
          export GIT_COMMITTED_AT=$(date +%s)
          export GIT_BRANCH=${{ github.ref_name }}
          export CHROME_BIN=${RUNNER_TOOL_CACHE}/chromium/latest/x64/chrome
          ../cc-test-reporter before-build
          `npm bin`/ng test --no-progress --browsers ChromeHeadlessNoSandbox
          ../cc-test-reporter after-build -t lcov --exit-code ${?} ./coverage/lconv.info
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
          CI_NAME: "Github Action"
          CI_BUILD_ID: ${{ github.run_number }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: e2e
        run: |
          export CHROME_BIN=${RUNNER_TOOL_CACHE}/chromium/latest/x64/chrome
          `npm bin`/ng e2e
