name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: "Enable pnpm"
        run: corepack enable
      - name: Install Dependencies
        run: pnpm i -s
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: |
          export GIT_COMMITTED_AT=$(date +%s)
          export GIT_BRANCH=$(basename ${{ github.repository }} ${{ github.repository_owner }})
          export CHROME_BIN=$(which chromium-browser)
          ../cc-test-reporter before-build
          pnpm run test -- --no-progress --browsers ChromeHeadlessNoSandbox
          ../cc-test-reporter after-build -t lcov --exit-code ${?} ./coverage/lconv.info
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
          CI_NAME: "Github Action"
          CI_BUILD_ID: ${{ github.run_number }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: e2e
        run: |
          export CHROME_BIN=$(which chromium-browser)
          pnpm run e2e
