name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: |
            ./node_modules
            ~/.cache/Cypress
      - uses: browser-actions/setup-chrome@latest
      - name: Install Dependencies
        run: pnpm i -s
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: |
          export GIT_COMMITTED_AT=$(date +%s)
          export GIT_BRANCH=${{ github.ref_name }}
          export CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
          pnpm run test --no-progress --browsers ChromeHeadlessNoSandbox
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
          CI_NAME: "Github Action"
          CI_BUILD_ID: ${{ github.run_number }}
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: ./coverage/lcov.info
      - name: Check cypress binary
        run: |
          if [ ! -d ~/.cache/Cypress ]; then
            pnpm run cypress:install
          fi
      - name: e2e
        run: |
          export CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
          pnpm run e2e
